heat_template_version: 2018-08-31

resources:
  mongodb:  
    type: OS::Nova::Server
    properties:
      name: MongoDB
      image: ed7d0907-565d-4a49-aa4c-67c86a5c3e08
      flavor: database-node
      key_name: cloud-ssh
      networks: [ {network: auth-app, fixed_ip: 192.168.65.52} ]
      security_groups: [default]
  instance:
    type: OS::Heat::ResourceGroup   
    properties:
      count: 3
      resource_def:
        type: OS::Nova::Server
        properties:
          name: app-%index%
          image: af497627-6eb6-4d75-b2d5-935bd1d8ae04
          key_name: cloud-ssh
          flavor: app-node
          networks: [ {network: auth-app} ]
          security_groups: [default]