heat_template_version: 2018-08-31

parameters:
  network_name:
    type: string
  subnet_name:
    type: string
  network_address:
    type: string
  gateway_ip:
    type: string
  router_name:
    type: string
  key_pair_name:
    type: string
  pub_key:
    type: string
  security_group_name:
    type: string
  security_groupe_rule:
    type: string
    default: "tcp"
  security_groupe_rule_port_min:
    type: string
    default: 0
  security_groupe_rule_port_max:
    type: string
    default: 65535

resources:
  networks:
    type: OS::Neutron::Net
    properties:
      name: {get_param: network_name}
      shared: false

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: networks}
      name: {get_param: subnet_name}
      cidr: {get_param: network_address}
      gateway_ip: {get_param: gateway_ip}
      dns_nameservers:
        - 8.8.8.8
      enable_dhcp: true

  router:
    type: OS::Neutron::Router
    properties:
      name: {get_param: router_name}
      external_gateway_info:
        network: public

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router}
      subnet: {get_resource: subnet}

  ssh_key_pairs:
    type: OS::Nova::KeyPair
    properties:
      name: {get_param: key_pair_name}
      public_key: {get_param: pub_key}

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: {get_param: security_group_name}

  security_group_rules:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: {get_resource: security_group}
      protocol: {get_param: security_groupe_rule}
      port_range_min: {get_param: security_groupe_rule_port_min}
      port_range_max: {get_param: security_groupe_rule_port_max}