heat_template_version: 2018-08-31

parameters:
  load_balancer_name:
    type: string
  load_balancer_subnet:
    type: string

resources:

  load_balancer:
    type: OS::Octavia::LoadBalancer
    properties:
      name: {get_param: load_balancer_name}
      vip_subnet: {get_param: load_balancer_subnet}