heat_template_version: 2018-08-31

parameters:
  load_balancer_name:
    type: string
  load_balancer_subnet:
    type: string
  listener_protocol:
    type: string
  listener_port:
    type: string
  algorithm:
    type: string
  monitor_type:
    type: string
    default: "PING"

resources:

  load_balancer:
    type: OS::Octavia::LoadBalancer
    properties:
      name: {get_param: load_balancer_name}
      vip_subnet: {get_param: load_balancer_subnet}

  listener:
    type: OS::Octavia::Listener
    properties:
      protocol: {get_param: listener_protocol}
      loadbalancer: {get_resource: load_balancer}
      protocol_port: {get_param: listener_port}

  pool:
    type: OS::Octavia::Pool
    properties:
      lb_algorithm: {get_param: algorithm}
      loadbalancer: {get_resource: load_balancer}
      protocol: HTTP
  pool_member1:
    type: OS::Octavia::PoolMember
    properties: 
      pool: {get_resource: pool}
      address: '192.168.65.41'
      protocol_port: 80
    
  pool_member2:
    type: OS::Octavia::PoolMember
    properties: 
      pool: {get_resource: pool}
      address: '192.168.65.57'
      protocol_port: 80

  pool_member3:
    type: OS::Octavia::PoolMember
    properties: 
      pool: {get_resource: pool}
      address: '192.168.65.48'
      protocol_port: 80
      
  monitor:
    type: OS::Octavia::HealthMonitor
    properties:
      type: {get_param: monitor_type}
      pool: {get_resource: pool}
      timeout: 5
      max_retries: 3
      delay: 5
  